name: New problem

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'problem name?'

jobs:
  run:
    uses: tw20000807/tps-actions/.github/workflows/new-problem.yml@main
    with:
      name: ${{ fromJson(github.event.inputs.name) }}
