name: New problem
inputs:
  name:
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Process
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        PROBLEMNAME: ${{ inputs.name }}
      run: |
        python3 create.py
