name: Build pdf

on:
  workflow_call:
    inputs:
      runs-on:
        default: 'ubuntu-latest'
        type: string

jobs:
  pre-build:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 3
    outputs:
      problems: ${{ steps.run-problems.outputs.problemsjson }}
      pdf: ${{ steps.run-problems.outputs.problems }}
      lastproblem: ${{ steps.run-problems.outputs.lastproblem }}
    steps:
      - uses: actions/checkout@v3

      - name: Allow Git to access workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Dump input context
        env:
          INPUT_CONTEXT: ${{ toJSON(inputs) }}
        run: echo "$INPUT_CONTEXT"

      - name: Get changes
        if: github.event_name == 'push'
        id: changes
        uses: tw20000807/tps-actions/.github/actions/get-changes@main

      - name: Check push
        if: github.event_name == 'push'
        env:
          CHANGES: ${{ steps.changes.outputs.changes }}
        run: |
          echo "$CHANGES"
          echo "REQUEST=${{ fromJson(steps.changes.outputs.changes).pdf }}" >> $GITHUB_ENV

      - name: Get problems
        id: all-problems
        uses: tw20000807/tps-actions/.github/actions/get-problems@main

      - name: Check dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "REQUEST=${{ steps.all-problems.outputs.problems }}" >> $GITHUB_ENV

      - name: Filter problems
        id: run-problems
        uses: tw20000807/tps-actions/.github/actions/run-problems@main
        with:
          requests: ${{ env.REQUEST }}

  build-pdf:
    needs: [pre-build]
    if: needs.pre-build.outputs.problems != '[]' || (github.event_name == 'workflow_dispatch')
    runs-on: ${{ inputs.runs-on }}
    container:
      image: tobiichi3227/tps-build-pdf-github-runner
      options: --user root
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Allow Git to access workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Check environment
        run: |
          echo ""
          pandoc -v
          echo ""
          xetex -v
          echo ""
          tps || :;
          echo ""
          fc-list | grep "Noto Sans Mono CJK TC" || :;
          echo ""
          pdfunite -v

      - name: Setup git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - uses: tw20000807/tps-actions/.github/actions/convert-images@main

      - name: Commit images
        run: |
          git status
          git pull
          git diff-index --quiet HEAD -- || git commit -m "Compress images"
          git push

      - name: Get problems
        id: all-problems
        uses: tw20000807/tps-actions/.github/actions/get-problems@main

      - name: Build pdfs
        run: |
          for prob in ${{ needs.pre-build.outputs.pdf }}; do
            echo "Build $prob"
            cd ${prob} && make statement && git add statement/index.pdf && cd ..
          done


      - name: Merge pdfs
        if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch')
        run: |
          make merge-pdfs
          git add attachments/problems.pdf

      - name: Commit pdf
        run: |
          git status
          git pull
          git diff-index --quiet HEAD -- || git commit -m "Build pdfs"
          git push
