name: Generate report

on:
  workflow_call:
    inputs:
      report-path:
        default: 'README.md'
        required: false
        type: string
      group-size:
        default: 3
        required: false
        type: number
      runs-on:
        default: 'ubuntu-latest'
        required: false
        type: string

jobs:
  generate:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3

      - uses: tw20000807/tps-actions/.github/actions/check-progress@main
        with:
          report-path: ${{ inputs.report-path }}

      - uses: tw20000807/tps-actions/.github/actions/list-subtasks@main
        with:
          report-path: ${{ inputs.report-path }}

      - uses: tw20000807/tps-actions/.github/actions/list-scores@main
        with:
          report-path: ${{ inputs.report-path }}
          group-size: ${{ inputs.group-size }}

      - name: Commit files
        run: |
          git add "${{ inputs.report-path }}"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git diff-index --quiet HEAD -- || git commit -m "Generate report"
          git push
